language: node_js
node_js: stable

branches:
  only:
    - master
    
env:
  global:
    - GH_REF: github.com/Charles-Lv/Charles-Lv.github.io.git

install:
  - npm install hexo-cli -g
  - npm install
before_script:
  - hexo clean

script:
  - hexo g

after_success:
  - cd ./public
  - git init
  - git config user.name "Charles-Lv"
  - git config user.email "i@lvhuan.me"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=8ca7ba912fc4f54f14f99aa64f116ea51a37bac4c21d39549514496bfed923f4
